config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'
  resources :posts do
    resources :replies
    
    collection do
      get :feeds
    end
    member do
      post :collect
      post :uncollect
    end
  end

  namespace :admin do
    root 'categories#index'
    resources :categories
    resources :users
  end

  resources :categories, only: :show

  resources :friendships, only: :create do
    member do
      post :accept
      delete :ignore
    end
  end

  resources :users do
    member do
      get :show_reply
      get :show_draft
      get :show_collect
      get :show_friend
    end
  end

  namespace :api, default: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_create :generate_authentication_token

  has_many :posts
  has_many :replies, dependent: :destroy
  has_many :collects, dependent: :destroy
  # 一個 user 收藏多筆 post，同一個 post 可以被不同的 user 收藏
  has_many :collected_posts, through: :collects, source: :post

  # 自己發出並被同意的邀請
  has_many :friendships, -> {where status: true}, dependent: :destroy
  has_many :friends, through: :friendships
  # 對方發出並已同意的邀請
  has_many :inverse_friendships, -> {where status: true}, class_name: "Friendship", foreign_key: "friend_id"
  has_many :inverse_friends, through: :inverse_friendships, source: :user
  # 自己發出並尚未同意的邀請
  has_many :request_friendships, -> {where status: false}, class_name: "Friendship", dependent: :destroy
  has_many :request_friends, through: :request_friendships, source: :friend
  # 對方發出並尚未同意的邀請
  has_many :inverse_request_friendships, -> {where status: false}, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy
  has_many :inverse_request_friends, through: :inverse_request_friendships, source: :user

  mount_uploader :avatar, AvatarUploader


  def generate_authentication_token
     self.authentication_token = Devise.friendly_token
  end

  def admin?
    self.role == "admin"
  end

  def friend?(user)
    self.friends.include?(user) || self.inverse_friends.include?(user)
  end

  # status: false
  def request_friend?(user)
    self.request_friends.include?(user)
  end

  # status: false
  def inverse_request_friend?(user)
    self.inverse_request_friends.include?(user)
  end

  def all_friends
    friends = self.friends + self.inverse_friends
    return friends.uniq
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  def index
    @users = User.page(params[:page]).per(10)
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:notice] = "#{@user.name}'s authority has been updated."
    else
      flash[:alert] = @user.errors.full_messages.to_sentence
    end
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user

  def show
    
    @posts = @user.posts.where(draft: false).page(params[:page]).per(10).order("posts.created_at DESC")
  end

  def edit
    
    unless @user == current_user
      flash[:alert] = "You have no access editing other people's profile."
      redirect_back fallback_location: root_path
    end    
  end

  def update
    
    if @user.update(user_params)
      flash[:notice] = "Updated successfully."
      redirect_to user_path(@user)
    else
      flash.now[:alert] = @user.errors.full_messages.to_sentence if @user.errors.any?
      render :edit
    end
  end

  def show_draft
    
    if @user == current_user
      @drafts = @user.posts.where(draft: true).order("posts.created_at DESC").page(params[:page]).per(10)
      render :show
    else
      flash[:alert] = "You have no access to other people's drafts."
      redirect_back fallback_location: root_path
    end
  end

  def show_reply
    
    @replies = @user.replies.order("replies.created_at DESC").page(params[:page]).per(10)

    render :show
  end

  def show_collect
    
    if @user == current_user
      @collects = @user.collected_posts.order("collects.created_at DESC").page(params[:page]).per(10)
      render :show    
    else
      @collects = @user.collected_posts.order("collects.created_at DESC").page(params[:page]).per(10)
      render :show
    end
  end

  def show_friend
    if @user == current_user
      @requests= @user.request_friends
      # 我邀請的人，還沒得到回覆
      @invites = @user.inverse_request_friends.order('friendships.created_at DESC')
      # 邀請我的人，還沒得到回覆
      @friends = @user.friends + @user.inverse_friends

      render :show
    else
      flash[:alert] = "Have no access to others' friendlist."
      redirect_back fallback_location: root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_collection.html.erb
<table class="table">
  <% if @collects.count == 0 %>
    <tr class= "bg-light-yellow">
      <th>Haven't collected any posts yet.<th>
    </tr>
  <% else %>
    <% @collects.each do |post| %>
    <tr class="bg-light-yellow" id="uncollectBar-<%= post.id %>">
      <th><%= link_to post.title, post_path(post) %></th>
      <% if @user == current_user %>
        <td>
          <%= link_to uncollect_post_path(post), method: :post, class: 'btn btn-light btn-sm' do %>
            <span class="fa-stacked">
              <i class="fa fa-heart"></i>
              <i class="fa fa-bolt fa-stack-1x fa-inverse"></i>
            </span>
            Uncollect
          <% end %>
        </td>  
      <% end %>
      
    </tr>
    <% end %> 
  <% end %>
</table>
<br>
<%= paginate @collects %>

app/views/users/_drafts.html.erb
<table class="table">
  <% if @drafts.count == 0 %>
    <tr class= "bg-light-yellow">
      <th>Have no drafts at present.<th>
    </tr>
  <% else %>
    <% @drafts.each do |draft| %>
    <tr class="bg-light-yellow">
      <th><%= link_to draft.title, post_path(draft) %></th>
      <td>draft</td>
      <td><%= draft.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
      <td>
        <%= render partial: 'shared/post-edit-btn', locals: {post: draft} %>
      </td>
    </tr>
    <% end %>
    <%= paginate @drafts %>
  <% end %>
</table>

app/views/users/_friends.html.erb
<% if @requests.exists? %>
  <div class="bg-light-yellow pb-5 pt-4">
    <div class="container"> 
      <div class="text-center">
        <h5 class="weight-700" style="color: gray">Waiting for Response</h5>
      </div>
      <br>
      <% @requests.each do |user| %>
        <%= render partial: 'shared/user-info2', locals: {user: user} %>
      <% end %>
      
    </div>
  </div>
<% end %>
<% if @invites.present? %>
  <div class="bg-dark-yellow pb-5 pt-4">
    <div class="text-center">
      <h5 class="weight-700" style="color: gray">Users that want to be friends</h5>
    </div>
    <br>
    <% @invites.each do |user| %>
      <%= render partial: 'shared/user-info2', locals: {user: user} %>
    <% end %>
  </div>
<% end %>
<% if @friends.present? %>
  <div class="bg-light-yellow pb-5 pt-4">
    <div class="text-center">
      <% if @user == current_user %>
        <h4 class="weight-700" style="color: gray">My Friendlist</h4> 
      <% elsif @user.admin? %>
        <h4 class="weight-700" style="color: gray"><%= @user.name %>'s Friendlist</h4>
      <% else %>
        <h4 class="weight-700" style="color: gray"><%= @user.name %>'s Friendlist</h4>
      <% end %>
    </div>
    <br>
    <% @friends.each do |user| %>
      <%= render partial: 'shared/user-info2', locals: {user: user} %>
    <% end %>
  </div>
<% end %>
<% if @friendsips.present? %>
  <div class="bg-light-yellow pb-5 pt-4">
    <div class="text-center">
      <h4 class="weight-700" style="color: gray">Read some posts, share some comments and make friends!</h4>
    </div>
  </div>
<% end %>

app/views/users/_posts.html.erb
<table class="table">
  <% if @posts.count == 0 %>
    <tr class= "bg-light-yellow">
      <th>Have no posts yet.<th>
    </tr>
  <% else %>
    <% @posts.each do |post| %>
    <tr class="bg-light-yellow">
      <th><%= link_to post.title, post_path(post) %></th>
      <td>published</td>
      <td><%= post.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
      <% if post.user == current_user %>
      <td>
        <%= render partial: 'shared/post-edit-btn', locals: {post: post} %>
      </td>
      <% end %>
    </tr>
    <% end %>
  <% end %>
</table>
<br>
<%= paginate @posts %>

app/views/users/_replies.html.erb
<% if @replies.count == 0 %> 
  <table>    
    <tr class= "bg-light-yellow">
      <th>Haven't placed any comments.<th>
    </tr>
  </table>
<% else %>
  <div class="bg-light-yellow">
    <% @replies.each do |reply| %>
      <div class="my-comment-div">
        <div class="">
          <h5 class="float-left"><%= link_to reply.post.title, post_path(reply.post) %></h5>
          <em class="float-right"><%= reply.created_at.strftime("%Y-%m-%d %H:%M:%S") %></em>
          <div class="clearfix"></div>
        </div>
        
        <div class="user-comment-area mb-3">
          <%= reply.comment %>
        </div>
        <% if reply.user == current_user %>
          <%= render partial: 'shared/reply-edit-btn', locals: {reply: reply} %>
          <div class="clearfix"></div>        
        <% end %>
        
      </div>
    <% end %>
  </div>
<% end %>
<br>
<%= paginate @replies %>

app/views/users/edit.html.erb
<div class="container">
  <div class="margin-top-50">
    <%= simple_form_for @user do |f| %>
      <%= f.input :name, label: false %>
      <%= f.input :intro, label: false, input_html: { class: 'de-height', :rows => 6 } %>
      <div class="form-inline">
        <% if @user.avatar? %>
          <%= image_tag @user.avatar, width: '300px', class: 'img-thumbnail'%>
          <%= f.input :avatar, label: false, input_html: { class: 'btn btn-outline-info', style: "margin: 0 10px;"}%>
        <% else %>
          <%= f.input :avatar, label: "Upload Picture", label_html: { class: 'btn btn-outline-info', style: "margin: 0 10px;"} %>
        <% end %>
      </div>
      <div class="clearfix"></div>
      <hr>
      <%= f.button :submit, "Update", class: 'btn btn-outline-dark' %>
      <%= link_to "Cancel", :back, class: 'btn btn-outline-secondary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-info">
  <div class="container">
    <div class="row">
      <!--USER'S SELF-INTRODUCTION -->
      <div class="col-3">
        <div class="text-center py-5">
          <%= render partial: 'shared/user-info', locals: {user: @user} %>
        </div>
      </div>
      <div class="col-9 py-5">
        <p><%= @user.intro %></p>
        <% if @user == current_user %>
          <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-outline-dark' %>
        <% end %>
      </div>
    </div>
  </div>

</div>


<br>
<!-- personal articles -->
<div class="container">
  <% if @user == current_user %>
     <div class="text-center">
      <%= link_to 'New Post', new_post_path, class: 'btn btn-outline-dark' %>
    </div>
    <hr>
    
    <ul class="nav nav-tabs weight-700">
      <li class="nav-item">
        <%= link_to 'My Posts', user_path(@user), class: "nav-link #{'active' if action?('show')}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'My Comments', show_reply_user_path(@user), class: "nav-link #{'active' if action?('show_reply')}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'My Collection', show_collect_user_path(@user), class: "nav-link #{'active' if action?('show_collect')}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'My Drafts', show_draft_user_path(@user), class: "nav-link #{'active' if action?('show_draft')} " %>
      </li>
      <li class="nav-item">
        <%= link_to 'My Friends', show_friend_user_path(@user), class: "nav-link #{'active' if action?('show_friend')}" %>
      </li>
    </ul>

  <% else %>
  
    <br>
    <ul class="nav nav-tabs weight-700">
      <li class="nav-item">
        <%= link_to "#{@user.name}'s Posts", user_path(@user), class: "nav-link #{'active' if action?('show')}" %>
      </li>
      <li class="nav-item">
        <%= link_to "#{@user.name}'s Comments", show_reply_user_path(@user), class: "nav-link #{'active' if action?('show_reply')}" %>
      </li>
      <li class="nav-item">
        <%= link_to "#{@user.name}'s Collection", show_collect_user_path(@user), class: "nav-link #{'active' if action?('show_collect')}" %>
      </li>
      <li class="nav-item">
        <%= link_to "#{@user.name}'s friends", show_friend_user_path(@user), class: "nav-link #{'active' if action?('show_friend')}" %>
      </li>
    </ul>

  <% end %>

  
  <div class="row">
    <div class="col">
      <% if action?('show_draft') %>
        <%= render partial: 'drafts' %>
      <% elsif action?('show_reply') %>
        <%= render partial: 'replies' %>
      <% elsif action?('show_collect') %>
        <%= render partial: 'collection' %>
      <% elsif action?('show_friend') %>
        <%= render partial: 'friends' %>
      <% else %>
        <%= render partial: 'posts' %>
      <% end %>
    </div>
  </div>

</div>