config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'
  resources :posts do
    resources :replies
    
    collection do
      get :feeds
    end
    member do
      post :collect
      post :uncollect
    end
  end

  namespace :admin do
    root 'categories#index'
    resources :categories
    resources :users
  end

  resources :categories, only: :show

  resources :friendships, only: :create do
    member do
      post :accept
      delete :ignore
    end
  end

  resources :users do
    member do
      get :show_reply
      get :show_draft
      get :show_collect
      get :show_friend
    end
  end

  namespace :api, default: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/views/shared/_friend-btn.html.erb
<% if user != current_user %>
  <% if current_user.friend?(user) %>
    <span class='badge badge-info'>Friend</span>
  <% else %>
    <% if current_user.inverse_request_friend?(user) %> <!-- 他已經先邀請我了 -->
      <%= button_to "Accpet", accept_friendship_path(user), class: "btn btn-outline-success mb-1 btn-wide", method: :post %>
      <%= button_to "Ignore", ignore_friendship_path(user), class: "btn btn-outline-dark btn-wide", method: :delete %>
    <% elsif current_user.request_friend?(user) %> <!-- 我先發邀請了 -->
      <button type="button" class='btn btn-outline-secondary disabled btn-wide'>Waiting...</button>
    <% else %> <!-- 還不是朋友 -->
      <%= link_to friendships_path(friend_id: user), class: "btn btn-outline-success btn-wide", method: :post do %>
        <%= fa_icon 'plus' %> Friend
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <span class='badge badge-secondary'>Me</span>
<% end %>

app/views/shared/_friend-info.html.erb
<%= link_to user_path(user) do %>
  <% if user.avatar? %>
    <%= image_tag user.avatar, width: '100px', class: 'img-thumbnail' %>
  <% else %>
    <div class="text-center">
      <%= fa_icon 'user-circle-o 3x' %>
    </div>
  <% end %>
  <h5 class="mt-3"><%= user.name %></h5>
<% end %>
<%= invite_btn(user) %>

app/views/shared/_post-edit-btn.html.erb
<%= link_to edit_post_path(post) do %>
  <%= fa_icon 'edit', style: 'font-size: 27px;' %>
<% end %>
<%= link_to post_path(post), method: :delete, data: {confirm: "Are you sure?"} do %>
  <%= fa_icon 'times', style: 'border: 2px solid #007bff; border-radius: 3px; padding: 2px 4px;' %>
<% end %>  

app/views/shared/_post-form.html.erb
<div class="container">
  <div class="margin-top-50">
    <%= simple_form_for @post do |f| %>
      <%= f.input :title, label: false, placeholder: 'Title' %>
      <%= f.input :content, label: false, as: :text, :input_html => { class: 'de-height', :rows => 12 } %>
      <div>
        <%= image_tag @post.image, width: '300px', class: 'img-thumbnail mb-3' if @post.image? %>
      </div>
      <div>
        <%= f.input :image, label: false, input_html: {class: 'btn btn-outline-info'} %>
      </div>

      <hr>
      
      <div class="container">
        <div class="row">
          <div class="col-8">
            <%= f.input :privacy, as: :radio_buttons, collection: [[ :all_user, "all"], [ :only_friend, "friends"], [:only_me, "me"]], label_method: :second, value_method: :first, wrapper: :vertical_collection_inline %>
            <%= f.association :categories, label: false, as: :check_boxes, collection: @categories, input_html: {multiple: true}, wrapper: :vertical_collection_inline %>
          </div>
          <div class="col-4">
            <div class="float-right">
              <h5>Status:</h5>
              <%= f.button :submit, 'Save as Draft', class: 'btn btn-outline-dark', name: 'commit' if @post.draft == true %>
              <%= f.button :submit, 'Publish', name: 'commit', class: 'btn btn-outline-info' %>
            </div>
            <div class="clearfix"></div>
          </div>
          <hr>
          <%= link_to 'Back', :back, class: 'btn' %>
        </div>  
      </div>
      
    <% end %>
  </div>
</div>

app/views/shared/_post-table.html.erb
<table class="table container">
  <thead class="thead-light thead-font w-100">
    <tr class="row">
      <th class="col-2 text-center"><%= sort_link(@q, :replies_count, 'Replies Count', default_order: :desc) %></th>
      <th class="caret-gone col-6"><%= fa_icon 'sort', style: 'color: #6c757d;' %> <%= sort_link(@q, :title, 'Title', default_order: :desc) %></th>
      <th class="col-2 text-center"><%= sort_link(@q, :last_replied_at, 'Last Replied at', default_order: :desc) %></th>
      <th class="col-2 text-center"><%= sort_link(@q, :viewed_count, 'Viewed Count', default_order: :desc) %></th>
    </tr>
  </thead>
  
  <tbody class="w-100">
    <% @posts.each do |p| %>
      <tr class="row">

        <td class="col-2 text-center"><%= p.replies_count %></td>
        <td class="col-6">
          <b><%= link_to p.title, post_path(p) %></b>
          <% p.categories.each do |category| %>
            <%= link_to category.name, category_path(category), class: "badge index-badge" %>
          <% end %>
        </td>
        <!-- 印出本 post 最後的 reply 的 建立時間 -->
        <td class="col-2 text-center">
          <% if p.last_replied_at.present? %>
            <%= p.last_replied_at.strftime("%Y-%m-%d %H:%M:%S") %>
          <% else %>
            <span style="color: gray;">No replies yet</span>
          <% end %>                
        </td>
        <td class="col-2 text-center"><%= fa_icon 'eye' %> <%= p.viewed_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_reply-edit-btn.html.erb
<div class="comment-edit">
  <%= link_to edit_post_reply_path(reply.post, reply) do %>
    <%= fa_icon 'edit', style: 'font-size: 27px;' %>
  <% end %>
  <%= link_to post_reply_path(reply.post, reply), method: :delete, data: {confirm: "Are you sure?"} do %>
    <%= fa_icon 'times', style: 'border: 2px solid #007bff; border-radius: 3px; padding: 2px 4px;' %>  
  <% end %>
</div>

app/views/shared/_user-info.html.erb
<%= link_to user_path(user), class: 'profile-link' do %>
  <% if user.avatar? %>
    <%= image_tag user.avatar, width: '150px', class: 'img-thumbnail' %>
  <% else %>
    <div class="text-center">
      <%= fa_icon 'user-circle-o 5x' %>
    </div>
  <% end %>
  <h4 class="mt-3"><%= user.name %></h4>          
<% end %>
<%= render partial: "shared/friend-btn", locals: {user: user} %>

app/views/shared/_user-info2.html.erb
<div class="inline-blk text-center">
  <%= link_to user_path(user), class: 'profile-link' do %>
    <% if user.avatar? %>
      <%= image_tag user.avatar, width: '100px', class: 'img-thumbnail' %>
    <% else %>
      <div class="text-center pb-3">
        <%= fa_icon 'user-circle-o 4x' %>
      </div>
    <% end %>
    <h5 class="mt-3"><%= user.name %></h5>
  <% end %>
  <%= render partial: 'shared/friend-btn', locals: {user: user} %>
</div>

app/views/shared/_user-item.html.erb
<div class="text-center">
  <%= link_to user_path(user) do %>
    <%= image_tag user.avatar, width: 80, height: 80 if user.avatar? %>
    <div class="avatar_name"><%= user.name %></div>
  <% end %>
</div>
<div class="friend_button" id="user-<%= user.id %>"><!-- Ajax prepare -->
  <%= render partial: "shared/friend_button", locals: { user: user } %>
</div>