config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'
  resources :posts do
    resources :replies
    
    collection do
      get :feeds
    end
    member do
      post :collect
      post :uncollect
    end
  end

  namespace :admin do
    root 'categories#index'
    resources :categories
    resources :users
  end

  resources :categories, only: :show

  resources :friendships, only: :create do
    member do
      post :accept
      delete :ignore
    end
  end

  resources :users do
    member do
      get :show_reply
      get :show_draft
      get :show_collect
      get :show_friend
    end
  end

  namespace :api, default: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user, counter_cache: true
  has_many :collects, dependent: :destroy
  has_many :collectors, through: :collects, source: :user
  
  has_many :replies, dependent: :destroy # post 被刪，其下的 replies 也要被刪，但 user 會在
  # 一個 post 有多個 categories, 一個 category 屬於多個 post
  has_many :post_categoryships, dependent: :destroy # 某 post 被刪，跟這個 post 有關的 post-category 記錄也都會沒有
  has_many :categories, through: :post_categoryships
  
  mount_uploader :image, ImageUploader
  validates_presence_of [:content, :title]


  # 文章是否為草稿
  scope :draft, -> {
    where(draft: true)
  }

  scope :published, -> {
    where(draft: false)
  }

  # 沒有這個設定沒辦法寫入，privacy 會是 0
  enum privacy: {
    all_user:     1, # 公開
    only_friend:  2, # 好友限定
    only_me:      3, # 僅限自己

  # 1,2,3 只是順序，不能被 pass 進 tables
  }

  def is_collected?(user)
    self.collectors.include?(user)    
  end

  # 計算 viewed_count
  def count_views
    self.viewed_count += 1
    self.save
  end

  # 沒有 filter 到的感覺
  def self.access_posts(user)
    Post.where(privacy: "only_friend", user: user.all_friends).or( Post.where(privacy: "all_user")).or(Post.where(privacy: "only_me", user: user))
  end

  def be_viewed_by?(user) 
  # self 用在 post 上，只要符合其中一個條件就可以看到
  # 在首頁，user 以 current_user 為先決判斷條件；
  # 自己可以全部 user 的公開 post，加上我自己的，
  # 再加上和我是朋友關係的 user 的 朋友可見 post 就其全了。
    if self.user == user
      return true
    elsif self.draft && self.user == user
      return true
    elsif self.privacy == 'only_me' && self.user == user
      return true
    elsif self.privacy == 'all_user' && !self.draft
      return true
    elsif self.privacy == 'only_friend'
      self.user.friends.where('friendships.status = ?', 'true').include?(user)
      return true
    else
      return false
    end
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApiController
  before_action :authenticate_user!, except: :index
  before_action :set_post, only: [:show, :update, :destroy]

  def index
    @categories = Category.all
    if current_user

      if params[:category_id]
        render json: {
          category:
          {
            name: @category.name
          },

          posts_data: @category.posts.map do |post|
            {
              title: post.title,
              content: post.content,
              image: post.image,
              privacy: post.privacy,
              draft: post.draft,
            }
          end
        }
      else
        @posts = Post.all
        render json: {
          posts_data: @posts.map do |post|
            {
              title: post.title,
              content: post.content,
              image: post.image,
              privacy: post.privacy,
              draft: post.draft,
            }
          end
        }
      end

    end
  end

  def show
    if current_user 
      if !@post
        render json: {
          message: "can't find the post!",
          status: 400
        }
      else
        if @post.count_views
          @replies = @post.replies
          render json: {
            title: @post.title,
            content: @post.content,
            image: @post.image,
            draft: @post.draft,
            privacy: @post.privacy,

            categories_data: @post.categories.map do |c|
              {
                name: c.name,
              }
            end,
            replies_data: @post.replies.map do |reply|
              {
                user: reply.user.name,
                comment: reply.comment,
              }
            end,
          }
        end
      end
    end
  end

  def create
      
    @post = current_user.posts.build(post_params) 
    
    if @post.save
      render json: {
        message: "A Post has been created.",
        result: @post
      }
    else
      render json: {
        errors: @post.errors
      }
    end
  end
  

  def update
    if @post.update(post_params)
      render json: {
        message: "Post updated successfully!",
        result: @post
      }
    else
      render json: {
        errors: @post.errors
      }
    end
  end

  def destroy
    @post.destroy
    render json: {
      message: "Post destroy successfully!"
    }
  end


  private

  def set_post
    @post = Post.find_by(id: params[:id])
  end

  def post_params
    params.permit(:title, :content, :image, :draft, :privacy, category_ids: [])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_post, only: [:show, :edit, :update, :collect, :uncollect, :destroy]

  def index
    @categories = Category.all
    if current_user
      if params[:category_id]
        @category = Category.find(params[:category_id])
        @q = @category.posts.access_posts(current_user).published.ransack(params[:q])
      else
        @q = Post.access_posts(current_user).published.ransack(params[:q])
      end
    else
      if params[:category_id]
        @category = Category.find(params[:category_id])
        @q = @category.posts.published.where(privacy: "all_user").ransack(params[:q])
      else
        @q = Post.published.where(privacy: "all_user").ransack(params[:q])
      end
    end
    
    @posts = @q.result.order(id: :asc).page(params[:page]).per(20)
  end

  def new
    @post = Post.new
    @categories = Category.all
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save && params[:commit] == 'Publish'
      @post.draft = false
      @post.save
      flash[:notice] = "Successfully published."
      redirect_to user_path(current_user)
    elsif @post.save
      redirect_to show_draft_user_path(current_user)
    else
      flash[:alert] = @post.errors.full_messages.to_sentence if @post.errors.any?
      render :new
    end
  end

  def show
    
    if @post.be_viewed_by?(current_user)
      @reply = Reply.new
      @replies = @post.replies.order("updated_at DESC").page(params[:page]).per(20)
      @post.count_views
      @post.save
    else
      flash[:alert] = 'The post is not open to you.'
      redirect_back fallback_location: root_path
    end
  end

  def edit
    if current_user.admin? && @post.user != current_user
      flash[:alert] = "Admin can't edit other people's posts!"
      redirect_back fallback_location: root_path
    elsif current_user.admin? && @post.user == current_user
      @categories = Category.all
    elsif @post.user == current_user
      @categories = Category.all
    else
      flash[:alert] = 'You have no access to this action!'
      redirect_back fallback_location: root_path
    end
  end

  def update
    
    if @post.update(post_params)
      if @post.draft == true && params[:commit] == 'Publish'
        @post.draft = false
        @post.save
        flash[:notice] = "\"#{@post.title}\" is successfully published."
      else
        flash[:notice] = "\"#{@post.title}\" has been updated."
      end
      redirect_to post_path(@post)
    else
      flash[:alert] = @post.errors.full_messages.to_sentence if @post.errors.any?
      render :edit
    end
  end

  def feeds
    @posts = Post.where(draft: false)
    @users = User.all
    @categories = Category.all
    @replies = Reply.all

    @popular_posts = @posts.order("posts.replies_count DESC").limit(10)
    @popular_users = @users.order("users.replies_count DESC").limit(10)
  end

  def collect
    
    @post.collects.create!(user: current_user)
    # redirect_back fallback_location: root_path
  end

  def uncollect
    
    collects = Collect.where(post: @post, user: current_user)
    collects.destroy_all
    # redirect_back fallback_location: root_path

    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.js
    end
  end

  def destroy
    
    if @post.user = current_user || current_user.admin?
      @post.destroy
      flash[:notice] = "Successfully deleted post \"#{@post.title}\"."
      redirect_to root_path
    else
      flash[:alert] = "Have no authority to this deleting action!"
      redirect_back fallback_location: root_path
    end
    
  end
  
  private

  def post_params
    params.require(:post).permit(:title, :content, :image, :draft, :privacy, :category_ids => [])
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_collect-btn.html.erb
<% if @post.is_collected?(current_user) %>
  <%= link_to uncollect_post_path(@post), method: :post, remote: true, class: 'btn btn-light' do %>
    <span class="fa-stacked">
      <i class="fa fa-heart"></i>
      <i class="fa fa-bolt fa-stack-1x fa-inverse"></i>
    </span>
    Uncollect
  <% end %>
<% else %>
  <%= link_to collect_post_path(@post), method: :post, remote: true, class: 'btn btn-dark' do %>
    <%= fa_icon 'heart' %>
    Collect
  <% end %>
<% end %>

app/views/posts/collect.js.erb
$("#collect").html("<%= j(render partial: 'collect-btn') %>")
// 一個 action 對應一個 js.erb file, 對同一個 id div 動作

app/views/posts/edit.html.erb
<%= render partial: 'shared/post-form' %>

app/views/posts/feeds.html.erb
<div class="user-info">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-9 row text-center py-5">
        <div class="col-4">
          <h4>Users</h4>
          <button class="feeds-btn">
            <%= @users.count %>
          </button>
        </div>

        <div class="col-4">
          <h4>Posts</h4>
          <button class="feeds-btn">
            <%= @posts.count %>
          </button>
        </div>

        <div class="col-4">
          <h4>Comments</h4>
          <button class="feeds-btn">
            <%= @replies.count %>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="margin-top-50">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-9 row text-center">
        <div class="col-5 pr-4">
          <div class="feeds-box-title">
            <h3>Chatterbox</h3>
          </div>
          <table class="table table-borderless">
            <% @popular_users.each do |user| %>
              <tr style="text-align: left;">
                <td>
                  <b><%= link_to user.name, user_path(user), style: "color: #3a72b3;" %></b>
                </td>
                <td style="color: #4d9bff;"><%= user.replies_count %> replies</td>
              </tr>
            <% end %>
          </table>
        </div>
        <div class="col-7 pl-4">
          <div class="feeds-box-title">
            <h3>Most Popular Posts</h3>
          </div>
          <table class="table table-borderless">
            <% @popular_posts.each do |post| %>
            <tr style = "text-align: left;">
              <td>
                <b><%= link_to post.title, post_path(post), style: "color: #3a72b3;" %></b>
              </td>
              <td style="color: #4d9bff;"><%= post.created_at.strftime("%Y-%m-%d") %></td>
            </tr>
            <% end %>
          </table>
        </div>
        
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="margin-top-50">
    <h1 class="page-title-h1"><%= link_to 'World Wild', root_path, style: 'color: #000; text-decoration: none;' %></h1>  
  </div>
  <div style="margin-top: 30px;">
    <ul class="nav nav-pills">
      <li role="presentation"><%= link_to "All", root_path, class: "btn category-tag #{'active' if @category.blank? } mr-3" %></li>
      <% @categories.each do |category| %>
        <li role="presentation">
          <%= link_to category.name, category_path(category), class: "btn category-tag mr-3 #{'active' if category == @category}" %>
        </li>
      <% end %>
    </ul>
  </div>
  <br>
  <%= render partial: 'shared/post-table' %>
  <br>
  <%= paginate @posts %>     
</div>

app/views/posts/new.html.erb
<%= render partial: 'shared/post-form' %>

app/views/posts/show.html.erb
<div class="post-show-title">
  <div class="container">
    <span class="weight-700 font-26"><%= @post.title %></span>
    <div class="float-right" id="collect">
      <%= render partial: 'collect-btn' %>
    </div>
  </div>
  <div class="clearfix"></div>
</div>
<!-- post article -->
<div class="row post-show-row">
  <div class="col-3">
    <div class="text-center py-5">
      <%= render partial: 'shared/user-info', locals: {user: @post.user} %>
    </div>
  </div>
  <div class="col-9 post-show-box pt-5 px-5">
    <% if @post.image? %>
      <%= image_tag @post.image, width: '450px', class: 'img-thumbnail' %><br><br>  
    <% end %>
    
    <p style="font-size: 20px;"><%= @post.content %></p>
    <div class="">
      <i style="color: #839cbb;">related tags: </i>
      <% @post.categories.each do |category| %>
        <%= link_to category.name, root_path, class: "badge badge-warning mr-2", style: 'font-size: 18px;' %>
      <% end %>
    </div>
    <% if @post.user == current_user || current_user.admin? %>
      <div class="comment-edit">
        <%= render partial: 'shared/post-edit-btn', locals: {post: @post} %>
      </div>
    <% end %>
  </div>

</div>

<!-- post's replies -->
<% if @post.replies %>
  <% @replies.each do |reply| %>
    <div class="row post-show-reply-row bg-light-yellow">
      <div class="col-3">
        <div class="text-center py-4">
          <%= link_to user_path(reply.user), class: 'profile-link' do %>
            <% if reply.user.avatar? %>
              <%= image_tag reply.user.avatar, width: '100px', class: 'img-thumbnail' %>
            <% else %>
              <div class="text-center">
                <%= fa_icon 'user-circle-o 3x' %>
              </div>
            <% end %>
            <h5 class="mt-3"><%= reply.user.name %></h5>
          <% end %>
          <%= render partial: "shared/friend-btn", locals: {user: reply.user} %>

        </div>
      </div>
      <div class="col-9 post-show-box py-4 px-5">
        <p><%= reply.comment %></p>
        <% if reply.user == current_user %>
          <%= render partial: 'shared/reply-edit-btn', locals: {reply: reply} %>
        <% end %>
      </div>
      
    </div>
  <% end %>
  <%= paginate @replies %>
<% end %>

<!-- comment textarea -->
<% if @post.draft == false %>
  <div class="py-4 px-5">
    <%= simple_form_for [@post, @reply] do |f| %>
      <%= f.input :comment, input_html: {rows: 5, style: "border-radius: 15px; padding: 20px 40px;"}, placeholder: "Leave comment:", label: false %>
      <%= f.submit "Submit", class: 'btn btn-outline-success float-right' %>
    <% end %>
    <div class="clearfix"></div>
  </div>
<% end %>

app/views/posts/uncollect.js.erb
$("#collect").html("<%= j(render partial: 'collect-btn') %>")
// 一個 action 對應一個 js.erb file, 對同一個 id div 動作