config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'
  resources :posts do
    resources :replies
    
    collection do
      get :feeds
    end
    member do
      post :collect
      post :uncollect
    end
  end

  namespace :admin do
    root 'categories#index'
    resources :categories
    resources :users
  end

  resources :categories, only: :show

  resources :friendships, only: :create do
    member do
      post :accept
      delete :ignore
    end
  end

  resources :users do
    member do
      get :show_reply
      get :show_draft
      get :show_collect
      get :show_friend
    end
  end

  namespace :api, default: {format: :json} do
    namespace :v1 do
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"
      resources :posts, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg sticky-top navbar-light bg-info">
  <strong><%= link_to 'World Wild', root_path, class: 'navbar-brand', style: 'color: #fff';%></strong>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Feeds', feeds_posts_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'All Post', posts_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'New Post', new_post_path, class: 'nav-link new-post' %>
      </li>
      
    </ul>

    <ul class="float-right navbar-nav">
      
      <% if current_user&.admin? %>
        <li><%= link_to 'Admin Panel', admin_categories_path, class: 'btn btn-sm btn-warning', style: 'margin-top: 5px;' %></li>
      <% end %>
      <% if current_user %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Hi, 
          <% if current_user.name.present? %>
            <%= current_user.name %>
          <% else %>
            Newbie!
          <% end %> 
          </a>
          <div class="dropdown-menu dropdown-menu-right text-center" aria-labelledby="navbarDropdown">            
            <%= link_to 'Profile', user_path(current_user), class: "dropdown-item" %>
            <%= link_to 'Passwords', edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>

          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log in', new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <div class="clearfix"></div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>World Wild</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <% if flash[:notice] %>
      <div class="alert alert-info"><%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger"><%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
    
  </body>
</html>